#pragma config(Sensor, S3,     HTGYRO,              sensorRawValue)
#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     ArmReset,            sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     rightm,        tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftm,         tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     arm,           tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    trapdoor,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    claws,                tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "joysticklib.c"

#include "servolib.c"
#include "armjoysticktest.c"

/*
Function: ArmToPosition()
Description:
Brings the arm to rack position or scoring position
parameters:
position: what position we want the arm to go to, rack or scoring.
returns: none
*/
void ArmToPosition_test(unsigned int Position)
{
  int targetVal =0;

  // calculate incremental target postition
  switch(Position)
  {
    case lowheight:
      targetVal = lowheight - nMotorEncoder[arm];
      break;
    case middleheight:
      targetVal = middleheight - nMotorEncoder[arm];
      break;
    case highheight:
      targetVal = highheight - nMotorEncoder[arm];
      break;
    case scoreheight:
      targetVal = scoreheight - nMotorEncoder[arm];
      break;
    default:

  }
  nxtDisplayTextLine(2, "tv:%d, nME:%d", targetVal,nMotorEncoder[arm]);
  //Move the arm up to Rack Position.
  //nMotorEncoderTarget[arm]= targetVal;

  //power the motor
  if(targetVal > 0)
  {
    motor[arm] = 80;

  }
  else
  {
    motor[arm] = -22;

  }

  //Wait until the motors stop moving
  //while ( (nMotorRunState[arm] != runStateIdle) )
  while((nMotorEncoder[arm] < targetVal)
  {
    wait1Msec(10);
  }
  motor[arm]=0;
  wait1Msec(1000);
}



task main()
{
  ResetArm();
  ArmToPosition_test(middleheight);

}
