#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S2,     touch,               sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     Arm,           tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    claw,                 tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_2,    trapdoor,             tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "joysticklib.c"
#include "servolib.c"
#define lowheight 250
#define middleheight 490
#define highheight 700

TJoystick joystick_sm;      // User defined variable access



task main()
{
  //Reset encoder count to 0
  nMotorEncoder[Arm]=0;
  while(true)
  {
    //If the down button on the Dpad is pressed, move the arm to score from the low dispenser
    if(IsDOWNJoy2DPadPressed(joystick_sm) == true)
    {
      //If the arm is above the lowheight, then give the motors negative power
      while(nMotorEncoder[Arm] > lowheight)
      {
        motor[Arm]=-30;
      }

      //If the arm is below the lowheight, give the motors positive power
      while(nMotorEncoder[Arm] < lowheight)
      {
        motor[Arm]=40;
      }
      motor[Arm]=0;
    }

    //If the left button on the Dpad is pressed, move the arm to score from the middle dispenser
    else if(isLEFTJoy2DPadPressed(joystick_sm) == true)
    {
      //If the arm is above the middleheight, then give the motors negative power
      while(nMotorEncoder[Arm] > middleheight)
      {
        motor[Arm]=-30;
      }
      //If the arm is below the middleheight, then give the motors positive power
      while(nMotorEncoder[Arm] < middleheight)
      {
        motor[Arm]=40;
      }
    }

    //If the up button on the Dpad is pressed, move the arm to score from the high dispenser
    else if(IsUPJoy2DPadPressed(joystick_sm) == true)
    {
      while(nMotorEncoder[Arm] < highheight)
      {
        motor[Arm] = 40;
      }
    }

    /*

    //If the right button on the Dpad is pressed, reset the arm
    if(isRIGHTJoy2DPadPressed(joystick_sm) == true)
    {
      while(SensorValue(touch) == 0)
      {
        motor[arm] = -30;
      }
      motor[arm]=0;
    }
    */

  }
}
