#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S3,     HTGYRO,              sensorRawValue)
#pragma config(Sensor, S2,     Touch,               sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     rightm,        tmotorNormal, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftm,         tmotorNormal, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     arm,           tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    trapdoor,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    hoop,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    lefthook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    claws,                tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//
//
////////////////////////////////////////////////////////////////////////////////////////////////////

//#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

// Our Includes

#define MIN_POWER 20

#include "joysticklib.c"

#include "servolib.c"
#include "drivelibrary.c"
#include "armjoysticktest.c"
#include "GyroLib.c"

void StopAllMotors()
{
  motor[leftm] = 0;
  motor[rightm] = 0;
  motor[arm] = 0;
}

void initializeRobot()
{
  ResetLasso();
  //reset the trapdoor
  ResetTrapdoor();
  ResetArm();
  CLAWS_STOP

  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
  // IN initialize period, we will make sure that the arm is in reset position.

  return;
}


task main()
{
  initializeRobot();
  waitForStart();

  // move arm up
  ArmToPosition(scoreheight);
  // turn towards rolling goal
  spinAntiClockWise(40, 500);

  // move forward towards goal

  moveFwd(50, 2850);

  // settle down
  wait1Msec(200);

  //moveFwd(15, 2000);
  //moveSpecial(8, 2000, 8, 2000);

  // open trap the door to release bottons
  ServoRotate(trapdoor,175);
  wait1Msec(2000);
  // move the arm up bit to clear any dangling batons
  motor[arm]=40;
  wait1Msec(200);
  motor[arm] = 0;
  ResetTrapdoor(); // close the trapdoor


  //pushing the rolling goal
  moveFwd(50,2000);

  // back little bit
  moveBwd(50,1250);

  // turn towards bridge
  spinAntiClockWise(80,4800);

  // lower the arm
  motor[arm]=-40;
  wait1Msec(2800);
  motor[arm] = 0;

  //Balance on bridge
  BalanceOnBridgeUsingGyro();

  StopAllTasks();
  //stop all the motors from moving.
  StopAllMotors();

}
