#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     Touch,               sensorTouch)
#pragma config(Sensor, S3,     HTGYRO,              sensorNone)
#pragma config(Sensor, S4,     HTMAG,               sensorNone)
#pragma config(Motor,  motorA,          lamp,          tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     rightm,        tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftm,         tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     arm,           tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    trapdoor,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    righthook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    lefthook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    claws,                tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "servolib.c"
#include "drivelibrary.c"
#include "ArmLib.c"
#include "Initialize.c"

task main()
{
  initializeRobotAuto();

  move(40,200, 40, 200);
  //move(-40,-1000, -40, -1000);
  //spinClockWise(50, 1500);
  //spinAntiClockWise(100, 500);
  //moveFwd(30, 1000);
  //moveBwd(40, 1000);

  while(true)
  {
    wait10Msec(10);
  }

}
