#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     Touch,               sensorTouch)
#pragma config(Sensor, S3,     HTGYRO,              sensorNone)
#pragma config(Sensor, S4,     HTMAG,               sensorNone)
#pragma config(Motor,  motorA,          lamp,          tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     rightm,        tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftm,         tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     arm,           tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    trapdoor,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    hoop,                 tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    lefthook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    claws,                tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//value for magnet sensor
#define magneticsensitivity 5

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
////////////////////////////////////////////////////////////////////////////////////////////////////

//#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

// Our Includes


long gMagValue = 0;

#include "joysticklib.c"
#include "drivelibrary.c"
#include "servolib.c"
#include "armjoysticktest.c"
#include "DriverTask.c"
#include "drivers/HTMAG-driver.h"
#include "Initialize.c"



// Our functions.
void StopAllMotors()
{
  motor[Arm] = 0;
}

//ALl of these functions are test functions that we used to test certain parts of our robots, such as motors, servos, etc.





//All of the functions above are test functions that we used to test certain parts of our robot, such as motors, servos, sensors, etc.

void ExternalBatteryPower()
{
	nxtDisplayTextLine(2, "Ext Batt:%4.1f V", externalBatteryAvg / (float) 1000);

}
void NXTBatteryPower()
{
	nxtDisplayTextLine(4, "NXT Batt:%4.1f V", nAvgBatteryLevel / (float) 1000);   // Display NXT Battery Voltage
}

void Blink()
{
    motor[lamp] = 100;
    wait1Msec(500);
    motor[lamp] = 0;
    wait1Msec(500);
}

task MonitorAndAlertTask()
{
  while(1)
  {
	  // Alert Ext. Bat power
	  if( (externalBatteryAvg / (float) 1000) < 13)
	    PlaySound(soundBeepBeep);

	  if( (nAvgBatteryLevel / (float) 1000) < 8)
	    PlaySound(soundLowBuzz);

	  wait1Msec(4000);
  }
}

task DetectMagneticBaton()
{
  //Calibrating the sensor
  nxtDisplayTextLine(2, "Bias: %4d", HTMAGstartCal(HTMAG));
  PlaySound(soundBlip);
  while(bSoundActive);

  while(true)
  {
    // Start the calibration and display the offset
    gMagValue = HTMAGreadVal(HTMAG);
    eraseDisplay();
    //play a sound if the magnet is detected
    if(gMagValue > magneticsensitivity)
    {
      //PlaySound(soundBeepBeep);
      //while(bSoundActive);
      Blink();
    }
    wait1Msec(100);
  }
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////



/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{

  initializeRobotTeleOp();

  waitForStart();   // wait for start of tele-op phase

  	///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////
	  ////                                                   ////
	  ////      Add your robot specific tele-op code here.   ////
	  ////                                                   ////
	  ///////////////////////////////////////////////////////////
	  ///////////////////////////////////////////////////////////

    // Insert code to have servos and motors respond to joystick and button values.

    // Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
    // You may be able to find "snippets" of code that are similar to the functions that you want to
    // perform.

  // Start DetectMagneticBaton task
  StartTask(DetectMagneticBaton);

  //Start the task to navigate the robot around the field with joystick.
  StartTask(DriveRobot);
  //Start the task to control the arm that scores points.
  StartTask(ArmControlTask);
  //Wait until the FMS disables our robot
  while(true)
  {
    alive();   // keep it alive
    wait10Msec(2);
  }

  //stop all the tasks
  StopAllTasks();
  //stop all the motors from moving.
  StopAllMotors();
}
