#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S2,     Touch,               sensorTouch)
#pragma config(Sensor, S3,     HTGYRO,              sensorNone)
#pragma config(Sensor, S4,     HTMAG,               sensorNone)
#pragma config(Motor,  motorA,          lamp,          tmotorNormal, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     rightm,        tmotorNormal, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftm,         tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     arm,           tmotorNormal, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorNormal, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    trapdoor,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    righthook,            tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    lefthook,             tServoStandard)
#pragma config(Servo,  srvo_S1_C2_6,    claws,                tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//#include "joysticklib.c"

#include "servolib.c"
#include "ArmLib.c"

task main()
{
  //Call the reset hooks function to reset the hooks
  ResetHooks();

  //wait1Msec(2000);
}
